apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dyrvold-dev-zerossl
  namespace: cert-manager
spec:
  acme:
    email: fredrik@dyrvold.dev
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: vZk-UoY3zFo6utAPnKm1hQ
      keySecretRef:
        name: zero-ssl-eab-credentials
        key: EAB_HMAC_KEY
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: cert-zerossl
    solvers:
      - dns01:
          azureDNS:
            clientID: d270037e-e947-4f6e-bb62-f0dbcdeb3bc8
            clientSecretSecretRef:
              # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
              name: azuredns-config
              key: client-secret
            subscriptionID: 7792876c-8c43-4031-acb9-5b65fa514deb
            tenantID: 94999c36-9100-4153-9cbc-ddce798f5c95
            resourceGroupName: galaxy
            hostedZoneName: dyrvold.dev
            # Azure Cloud Environment, default to AzurePublicCloud
            environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-cert
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: sample-cert
  subject:
    organizations:
      - dyrvold
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: test-cert.dyrvold.dev
  # At least one of a DNS Name, URI, IP address or otherName is required.
  dnsNames:
    - test-cert.dyrvold.dev
  # Issuer references are always required.
  issuerRef:
    name: dyrvold-dev-zerossl
    kind: ClusterIssuer