apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config-claim
  namespace: emby
  labels:
    app: emby
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  volumeName: "emby-config-volume"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-config-volume
  namespace: emby
  labels:
    app: emby
spec:
  claimRef:
    namespace: emby
    name: emby-config-claim
  storageClassName: microk8s-hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/k8s-emby-config"
