apiVersion: v1
kind: Service
metadata:
  name: emby
  labels:
    app: emby
  namespace: emby
spec:
  ports:
    - port: 8920
      protocol: TCP
      targetPort: 8920
      name: https
    - port: 8096
      protocol: TCP
      targetPort: 8096
      name: http
  selector:
    app: emby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  labels:
    app: emby
  namespace: emby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
        - name: emby
          image: emby/embyserver:latest
          ports:
            - containerPort: 8096
            - containerPort: 8920
          volumeMounts:
            #- name: emby-config
            #  mountPath: /config/config/system.xml
            #  subPath: config-system.xml
            - name: emby-data
              mountPath: /mnt/emby-data
      volumes:
        - name: emby-config
          configMap:
            name: emby-config
        - name: emby-data
          persistentVolumeClaim:
            claimName: emby-media-claim
