apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-media-claim
  namespace: emby
  labels:
    app: emby
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  volumeName: "emby-media-volume"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-media-volume
  namespace: emby
  labels:
    app: emby
spec:
  claimRef:
    namespace: emby
    name: emby-media-claim
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/k8s-emby"
